### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by nightah** [midwan/MB_SubSonic#1]
It appears that when specifying a https frontend for the subsonic server the following error is encountered:

> Error: The remote server returned an error: (400) Bad Request.

I can see the request getting to my reverse proxy as HTTP/1.1. Looks like it's trying to negotiate as http on port 443.

`[22/Feb/2016:14:22:26`` +1100] "GET /subsonic/rest/ping.view?u=admin&t=5ba991b4561efdc220c36b721561e1d0&s=09524d64e291f9225011df&v=1.13.0&c=MusicBee HTTP/1.1" 400 271 "-" "-"`

**Comment by midwan** [comment]
You're correct, currently it only uses HTTP connections. 
How did you enable HTTPS on the Subsonic server? I didn't see an option for that in my installation, including the option for setting up the certificate etc.

**Comment by midwan** [comment]
Nevermind, I found the related documentation: http://www.subsonic.org/pages/getting-started.jsp#4

I'll fix this one in the plugin by providing a dropdown list with the two protocol options (HTTP/HTTPS). That way, you won't have to type the address in the hostname (as it is now).

**Comment by nightah** [comment]
Great I'll keep a look out to see when you push changes, I'm happy to test and report back.

Also not that it should matter, but just for clarity my Subsonic server isn't HTTPS enabled. The frontend (nginx) acting as a reverse proxy is HTTPS/SSL enabled and is routing requests to the backend (Subsonic) running on standard HTTP.

**Comment by midwan** [comment]
Actually it does matter a bit, as the behavior is different. If you enable HTTPS on your Subsonic server, then all HTTP calls made to it will be automatically forwarded to the SSL port. In this case, the plugin will function even without this suggested improvement.

Regardless, I will implement this since I believe it's a good idea to have. :)

**Comment by midwan** [comment]
v2.1 added HTTPS support, so you can now configure it accordingly. The settings persists in the configuration together with the rest - though this means that your existing configuration is invalid with this version (also due to the fact that this version adds encryption in the configuration file).
A Wiki article should document this change for people upgrading.
Also, if anyone is using the *.subsonic.org domain, they should NOT use the HTTPS connection - they do not seem to support it (i.e. it does not forward to your local server). Instead, use the normal HTTP connection option and if your server has HTTPS enabled, it will forward you to that automatically.
