### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by DarrenS97** [midwan/MB_SubSonic#10]
https://www.reddit.com/r/subsonic/comments/4v5gil/musicbee/

> I'm in need of a client to use with Subsonic.
I went with MusicBee because it's supported by specific Rainmeter skins that I use.
However in the process of trying to connect to my subsonic server I get the error message "The Subsonic Server Did Not Respond As Expected" - http://puu.sh/qinQ3.png
Server settings: http://puu.sh/qinSm.png
MusicBee settings:
Protocol: HTTP
Hostname: *****.subsonic.org
Port: 4040
Path: "/"
And then respective username + pass.
Can anyone send me out some information on what the possible error could be?
Please and thank you <3

> Did you try connecting to the server a different way e.g. your browser, to make sure the server isn't down?

> Yes, I am personally connected to the server. Ports are also forwarded because another person was connected to the server with me downloading data.
http://puu.sh/qj3hU.png

**Comment by midwan** [comment]
The error message indicates that the plugin tried to contact the Subsonic server using the details provided and send a "ping" request. If all goes well, Subsonic sends back a standard request indicating a success. If it doesn't, you will get this error message to notify you.

In other words, your Subsonic server did not respond with an "OK" to the API's ping request.

This may be due to a firewall blocking access to it also. Is it accessible through a normal web browser on the same address? Can you try with an IP address instead of a hostname, in case it's a DNS resolution problem?

**Comment by DarrenS97** [comment]
Successfully connected through IP address rather than hostname.

**Comment by midwan** [comment]
OK, then it's a DNS resolution problem. The hostname you used did not resolve to the IP you currently have. This is a rather common problem with dynamic DNS services, if they don't update the IP you have often enough.

I believe we can close this issue then, as it's not related to the plugin. :)
