### ISSUE TITLE
Dragging files into playlist results in error

### ISSUE THREAD

**Issue by nightah** [midwan/MB_SubSonic#16]
It appears that when dragging files from within the search pane into the playing tracks window results in the following error:

> The source file for track 'xxxx' could not be found

If the file from within the search pane is right clicked and set to queue last, queue next or play now all of these options appear to work.

This is Subsonic 6.0 running on Arch Linux with MusicBee 3.0.5995 and MB_SubSonic 2.8beta.

**Comment by midwan** [comment]
I don't see this problem with MusicBee 3.0.6068 in my environment, could you please try upgrading to that and see if it's still an issue?

**Comment by nightah** [comment]
Couldn't find 3.0.6068, installed 3.0.6067 tried it and had the same problem.
Also updated to 3.0.6087 and had the same problem. Are there any specific logs that I should be looking at to try find more information?

**Comment by midwan** [comment]
The current stable release is 3.0.6068, although the download link mentions 3.0.6067:
![image](https://cloud.githubusercontent.com/assets/3877365/18197020/59b171d0-70f5-11e6-95be-8bc5cb31f816.png)

I still can't see the problem here, so we'll need some more details. 
Check your %APPDATA%\MusicBee folder for the logs, there should be an ActivityLog.dat, ErrorLog.dat and a few others there. Try cleaning them up before you test again, so that the won't contain too much information.

Once you try it out and replicate the problem, close down Musicbee and copy the logs here so we can check.

**Comment by midwan** [comment]
No feedback received, closing.
