### ISSUE TITLE
No tracks listed from supysonic server

### ISSUE THREAD

**Issue by lunik1** [midwan/MB_SubSonic#45]
Hi. I am using supysonic server but this plugin does not seem to support it. The server responds to ping as expected but no tracks are listed under the server in musicbee.

Supysonic targets version 1.8 of the Subsonic API, which as far as I understand is lower than the version targeted by this plugin. I have tried switching to a hex-encoded password which fixed a missing parameter error but no luck beyond that.

**Comment by midwan** [comment]
The minimum version of the API supported by the plugin is v1.13, so it might be due to that.
I'm afraid there's no easy way around this, as supporting older versions would require considerable effort with the current implementation (several things have changed since 1.8).

Is there a reason you can't use another Subsonic-compatible server? E.g. AirSonic?

**Comment by lunik1** [comment]
supysonic is much lighter on resources, which helps since I'm running on a pi, but since it's not likely to be supported I'll look into it. Thanks!

**Comment by jalabulajunx** [comment]
Airsonic should work on pi. I have been running Airsonic on pi3 for the last one year.
