### ISSUE TITLE
Password change is not handled well

### ISSUE THREAD

**Issue by andocromn** [midwan/MB_SubSonic#55]
I recently changed my password on my subsonic server, musicbee was very unhappy.  kept looping and error message but but did not prompt to update it.  I was able to update it but had to kill the app and restart.    NBD just figured I'd let you know  keep up the great work and stay healthy  

thanks always 
-Ryan

**Comment by midwan** [comment]
You can change the password from the plugin's Settings window, then re-save the settings.
However, MusicBee will automatically try to load the last opened file/folder on startup. If that was on Subsonic's server, then it will keep trying and failing (because of the incorrect password), without letting you get a chance to go in the Settings window.

I'm afraid I cannot do something about that however, as it's outside my control.

Another approach would be to delete your plugin settings file, which will cause it to start up without any configured username/password.
