### ISSUE TITLE
【Bug Report】Ping command failed when opening configuration panel for the second time.

### ISSUE THREAD

**Issue by Creling** [midwan/MB_SubSonic#59]
**Describe the bug**
It is a strange problem. When I type in username and password for the first time and ping, the pong is normal. However, after clicking save and then re-open configuration panel and do nothing other than ping again, the pong is wrong.

**To Reproduce**
I make a screen record:

![SfOj1M8v4E](https://user-images.githubusercontent.com/43109504/111911510-e0738680-8aa0-11eb-8054-f9e28f79dcb8.gif)

**Desktop**
 - OS: windows10 19042.746
 - Version v2.31 
 - MusicBee Version: MusicBeePortable_3_3_Update6

**Adition**
This may not be able to reproduce in your end, however, please give me some help or some suggestions. I have tried the Portable Edition, Installer Edition and even UWP Edition of MusicBee, and this problem always exists. :(

**Comment by midwan** [comment]
Wow, that is interesting indeed. I wonder what happens in the background to cause this kind of behavior.
Does the rest of the functionality work, however?

**Comment by Creling** [comment]
> Wow, that is interesting indeed. I wonder what happens in the background to cause this kind of behavior.
> Does the rest of the functionality work, however?

For MusicBee, other functions are OK.
For MB_SubSonic, all functions do not work. They will show a similar error message like the pong.

**Comment by Creling** [comment]
I find some strings in `subsonicSettings.dat` but they seems to be encrypted. Could you tell me how to decrypted them?

**Comment by midwan** [comment]
You can't decrypt them (at least, not easily - that's the point), but you can delete the file and recreate the settings if you want.

**Comment by Creling** [comment]
> You can't decrypt them (at least, not easily - that's the point), but you can delete the file and recreate the settings if you want.

I have tried to delete the file, and mb_subsonic is initialized. However, the problem still exists.
So could you tell me how to create a file with arbitrary configuration directly？

**Comment by midwan** [comment]
You can't create the file that way, it's encrypted from the plugin and it's expected to be encypted, otherwise it won't be read back correctly. If you recreated the settings from scratch, then the problem is not in the settings, but somewhere else.

You can call your server's endpoint manually (e.g. with a browser or a dedicated tool like Postman), if you know the URL. This page has the documentation for the API: http://www.subsonic.org/pages/api.jsp - you'd be interested in the Ping initially, to see how it behaves: http://www.subsonic.org/pages/api.jsp#ping
